### ISSUE TITLE
_csv.Error: line contains NUL

### ISSUE THREAD

**Issue by Joe-Heffer-Shef** [Joe-Heffer-Shef/maccor-python-example#1]
The `MACCORExtractor` fails to parse a binary MACCOR file (`LM_24.2.23_C1.004`) because it expects a CSV (ASCII) file input to `MACCORExtractor.generate_dataframe`.

```(maccor) C:\Users\cs1jsth\maccor-python-example>python maccor-example.py --path ./maccor_files
INFO:__main__:MACCOR group: ['maccor_files\\LM_24.2.23_C1.004']
Traceback (most recent call last):
  File "C:\Users\cs1jsth\maccor-python-example\maccor-example.py", line 49, in <module>
    main()
  File "C:\Users\cs1jsth\maccor-python-example\maccor-example.py", line 43, in main
    data = extractor.parse_to_dataframe(group)
  File "C:\Users\cs1jsth\Miniconda3\envs\maccor\lib\site-packages\batdata\extractors\base.py", line 76, in parse_to_dataframe
    df_out = self.generate_dataframe(file, file_number, start_cycle, start_time)
  File "C:\Users\cs1jsth\Miniconda3\envs\maccor\lib\site-packages\batdata\extractors\maccor.py", line 42, in generate_dataframe
    df = pd.read_csv(file, skiprows=1, engine='python', sep='\t', index_col=False, encoding="ISO-8859-1")
  File "C:\Users\cs1jsth\Miniconda3\envs\maccor\lib\site-packages\pandas\util\_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\cs1jsth\Miniconda3\envs\maccor\lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\cs1jsth\Miniconda3\envs\maccor\lib\site-packages\pandas\io\parsers\readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\cs1jsth\Miniconda3\envs\maccor\lib\site-packages\pandas\io\parsers\readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Users\cs1jsth\Miniconda3\envs\maccor\lib\site-packages\pandas\io\parsers\readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "C:\Users\cs1jsth\Miniconda3\envs\maccor\lib\site-packages\pandas\io\parsers\readers.py", line 1753, in _make_engine
    return mapping[engine](f, **self.options)
  File "C:\Users\cs1jsth\Miniconda3\envs\maccor\lib\site-packages\pandas\io\parsers\python_parser.py", line 122, in __init__
    ) = self._infer_columns()
  File "C:\Users\cs1jsth\Miniconda3\envs\maccor\lib\site-packages\pandas\io\parsers\python_parser.py", line 382, in _infer_columns
    line = self._buffered_line()
  File "C:\Users\cs1jsth\Miniconda3\envs\maccor\lib\site-packages\pandas\io\parsers\python_parser.py", line 620, in _buffered_line
    return self._next_line()
  File "C:\Users\cs1jsth\Miniconda3\envs\maccor\lib\site-packages\pandas\io\parsers\python_parser.py", line 719, in _next_line
    next(self.data)
_csv.Error: line contains NUL
```

**Comment by Joe-Heffer-Shef** [comment]
The input file is not CSV, but a proprietary binary format:
```
$ head maccor_files/LM_24.2.23_C1.004
▒▒▒+T▒▒
▒▒▒N▒9▒C▒D▒cG;▒ ▒(▒▒=▒@▒@▒3r?▒▒DN▒▒?▒▒▒\u▒?8;▒Êc▒?▒▒▒▒▒?▒9▒▒A'▒r?*▒▒D▒o?▒▒▒D^p?▒
▒Dx▒?Q▒`▒!UU▒5▒UU B▒▒▒▒▒F▒@@▒@▒▒▒▒▒▒@@▒?d▒@▒@^2r?t▒▒DH▒▒?▒n▒▒▒u▒??6▒a▒?W▒▒▒]▒▒?▒4▒▒▒▒▒r?▒C▒D▒o?tW▒D▒^p?3▒▒D▒?A3_▒!UU▒▒▒5▒▒T B▒▒▒▒▒F▒@@▒@▒▒▒▒▒▒@@▒?d▒A▒000000004608'LM 622 full formation.0002 cycles at C/10
▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ ▒▒+33▒
                                        33▒▒▒▒▒▒▒▒""!"p""3s""!"p""▒?▒?24 Jan 2023 4 Jan 2023 01/01/? 24:00     Build Test 2.0.1.2      2 cycles at C/10  Rest  ANNNStepTime = 08:00:00        002StepTime00:00:30  Do 1  AdvCycle Charge Current 0.1C    ANNNVoltage >= 4.2             005Voltage 0.005   StepTime00:01:00DischrgeCurrent 0.1C    ANNNVoltage <= 2.5             006Voltage 0.005   StepTime00:01:00 Loop 1 Loop Cnt = 2               007  End   <?xml version="1.0" encoding="UTF-8"?>
<?maccor-application progid="Maccor Procedure File"?>
<MaccorTestProcedure>
  <header>
    <BuildTestVersion>
      <major>1</major>
      <minor>5</minor>
```
